language: python
python:
  - "3.7"
 stages:
  - execute
  
jobs:
  include:
    - stage: execute
      name: "Running the Script"
      script:
      - echo $message 
      - python hello-world-travis.py
      - echo "Run  pytest"
      #- pytest -v --cov=calculator
